language: node_js
node_js:
- 0.1
deploy:
  provider: npm
  email: ed.sykes@gmail.com
  api_key:
    secure: Pbg3myj+X9w5gqWZ6uU1SnOxHI1M3/5fze7GbAP3C39pjeMFCJOmB20IOLt+BIwnSwPY/lJCCaew0C7nGDFXTIf/urtNvgOamzD3ST8j2YgPTNssBVSyinbhEP1hhQ1qrQ4lU7tmEfvyg+Qizw3wlduxsOVB/bG8qpJMqw03roo=
  on:
    tags: true
    repo: 1self/lib1self-server
    all_branches: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2a5a368d80efd6c35282
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false